import type { AbilityDef, PlayerClassId } from "./types.js";

export const ABILITIES: AbilityDef[] = [
  // ---------- WARDEN (melee, resolve) ----------
  {
    id: "warden_strike",
    classId: "warden",
    slot: 1,
    name: "Steel Strike",
    description: "A quick blade strike. Builds Resolve on hit.",
    resource: "resolve",
    resourceCost: 0,
    cooldownMs: 700,
    castTimeMs: 0,
    range: 3,
    radius: 0,
    effect: "damage",
    basePower: 8,
    powerScale: 0.9,
    maxRanks: 3
  },
  {
    id: "warden_shieldbash",
    classId: "warden",
    slot: 2,
    name: "Shield Bash",
    description: "Slam a foe, stunning it briefly.",
    resource: "resolve",
    resourceCost: 20,
    cooldownMs: 8000,
    castTimeMs: 0,
    range: 3,
    radius: 0,
    effect: "cc",
    basePower: 6,
    powerScale: 0.5,
    ccDurationMs: 1500,
    maxRanks: 3
  },
  {
    id: "warden_whirlwind",
    classId: "warden",
    slot: 3,
    name: "Whirlwind",
    description: "Spin, striking all nearby enemies.",
    resource: "resolve",
    resourceCost: 35,
    cooldownMs: 6000,
    castTimeMs: 300,
    range: 0,
    radius: 4.5,
    effect: "aoe_damage",
    basePower: 10,
    powerScale: 0.8,
    maxRanks: 3
  },
  {
    id: "warden_bulwark",
    classId: "warden",
    slot: 4,
    name: "Bulwark",
    description: "Brace, gaining a shield that absorbs damage for a few seconds.",
    resource: "resolve",
    resourceCost: 30,
    cooldownMs: 14000,
    castTimeMs: 0,
    range: 0,
    radius: 0,
    effect: "buff",
    basePower: 40,
    powerScale: 1.2,
    ccDurationMs: 6000,
    maxRanks: 3
  },
  {
    id: "warden_secondwind",
    classId: "warden",
    slot: 5,
    name: "Second Wind",
    description: "Tear victory from the brink, healing yourself.",
    resource: "resolve",
    resourceCost: 45,
    cooldownMs: 16000,
    castTimeMs: 0,
    range: 0,
    radius: 0,
    effect: "heal",
    basePower: 30,
    powerScale: 1.1,
    maxRanks: 3
  },

  // ---------- RANGER (ranged, focus) ----------
  {
    id: "ranger_quickshot",
    classId: "ranger",
    slot: 1,
    name: "Quickshot",
    description: "A fast, accurate arrow.",
    resource: "focus",
    resourceCost: 0,
    cooldownMs: 600,
    castTimeMs: 0,
    range: 16,
    radius: 0,
    effect: "damage",
    basePower: 7,
    powerScale: 0.85,
    maxRanks: 3
  },
  {
    id: "ranger_volley",
    classId: "ranger",
    slot: 2,
    name: "Piercing Volley",
    description: "Loose a volley that pierces everything in a line.",
    resource: "focus",
    resourceCost: 25,
    cooldownMs: 7000,
    castTimeMs: 200,
    range: 18,
    radius: 2,
    effect: "aoe_damage",
    basePower: 9,
    powerScale: 0.75,
    maxRanks: 3
  },
  {
    id: "ranger_trap",
    classId: "ranger",
    slot: 3,
    name: "Explosive Trap",
    description: "Plant a trap that roots and damages enemies who trigger it.",
    resource: "focus",
    resourceCost: 30,
    cooldownMs: 10000,
    castTimeMs: 0,
    range: 6,
    radius: 3,
    effect: "cc",
    basePower: 14,
    powerScale: 0.9,
    ccDurationMs: 2000,
    maxRanks: 3
  },
  {
    id: "ranger_evasive",
    classId: "ranger",
    slot: 4,
    name: "Evasive Shot",
    description: "Leap back while firing, gaining brief evasion.",
    resource: "focus",
    resourceCost: 20,
    cooldownMs: 9000,
    castTimeMs: 0,
    range: 16,
    radius: 0,
    effect: "damage",
    basePower: 6,
    powerScale: 0.6,
    ccDurationMs: 1200,
    maxRanks: 3
  },
  {
    id: "ranger_mark",
    classId: "ranger",
    slot: 5,
    name: "Hunter's Mark",
    description: "Mark a target, increasing all damage it takes.",
    resource: "focus",
    resourceCost: 25,
    cooldownMs: 14000,
    castTimeMs: 0,
    range: 18,
    radius: 0,
    effect: "debuff",
    basePower: 0.25,
    powerScale: 0,
    ccDurationMs: 8000,
    maxRanks: 3
  },

  // ---------- MYSTIC (caster/healer, aether) ----------
  {
    id: "mystic_moonbolt",
    classId: "mystic",
    slot: 1,
    name: "Moonbolt",
    description: "Hurl a bolt of lunar energy.",
    resource: "aether",
    resourceCost: 8,
    cooldownMs: 900,
    castTimeMs: 200,
    range: 16,
    radius: 0,
    effect: "damage",
    basePower: 9,
    powerScale: 1.0,
    maxRanks: 3
  },
  {
    id: "mystic_nova",
    classId: "mystic",
    slot: 2,
    name: "Lunar Nova",
    description: "Detonate a burst of Aether around a point.",
    resource: "aether",
    resourceCost: 30,
    cooldownMs: 7000,
    castTimeMs: 500,
    range: 14,
    radius: 4,
    effect: "aoe_damage",
    basePower: 11,
    powerScale: 0.9,
    maxRanks: 3
  },
  {
    id: "mystic_healingtide",
    classId: "mystic",
    slot: 3,
    name: "Healing Tide",
    description: "Wash healing energy over yourself and nearby allies.",
    resource: "aether",
    resourceCost: 35,
    cooldownMs: 9000,
    castTimeMs: 400,
    range: 0,
    radius: 8,
    effect: "aoe_heal",
    basePower: 16,
    powerScale: 1.1,
    maxRanks: 3
  },
  {
    id: "mystic_barrier",
    classId: "mystic",
    slot: 4,
    name: "Barrier",
    description: "Shield yourself, absorbing a burst of incoming damage.",
    resource: "aether",
    resourceCost: 28,
    cooldownMs: 12000,
    castTimeMs: 0,
    range: 12,
    radius: 0,
    effect: "buff",
    basePower: 35,
    powerScale: 1.1,
    ccDurationMs: 6000,
    maxRanks: 3
  },
  {
    id: "mystic_gravitywell",
    classId: "mystic",
    slot: 5,
    name: "Gravity Well",
    description: "Pull nearby enemies together and root them briefly.",
    resource: "aether",
    resourceCost: 32,
    cooldownMs: 15000,
    castTimeMs: 400,
    range: 14,
    radius: 5,
    effect: "cc",
    basePower: 5,
    powerScale: 0.4,
    ccDurationMs: 1800,
    maxRanks: 3
  }
];

export function abilitiesForClass(classId: PlayerClassId): AbilityDef[] {
  return ABILITIES.filter((a) => a.classId === classId).sort((a, b) => a.slot - b.slot);
}

export function getAbility(id: string): AbilityDef | undefined {
  return ABILITIES.find((a) => a.id === id);
}
