import { getItem } from "./items.js";
import type { AbilityDef, CharacterState, PlayerClassId } from "./types.js";

export const ABILITIES: AbilityDef[] = [
  // =========================================================================
  // WARDEN — melee, Resolve
  // =========================================================================

  // -- Sword & Board kit --
  {
    id: "warden_strike",
    classId: "warden",
    tier: "weapon",
    weaponType: "warden_sword_board",
    slot: 1,
    name: "Steel Strike",
    description: "A quick blade strike. Builds Resolve on hit.",
    resource: "resolve",
    resourceCost: 0,
    cooldownMs: 700,
    castTimeMs: 0,
    range: 3,
    radius: 0,
    effect: "damage",
    basePower: 8,
    powerScale: 0.9,
    maxRanks: 3
  },
  {
    id: "warden_shieldbash",
    classId: "warden",
    tier: "weapon",
    weaponType: "warden_sword_board",
    slot: 2,
    name: "Shield Bash",
    description: "Slam a foe, stunning it briefly.",
    resource: "resolve",
    resourceCost: 20,
    cooldownMs: 8000,
    castTimeMs: 0,
    range: 3,
    radius: 0,
    effect: "cc",
    basePower: 6,
    powerScale: 0.5,
    ccDurationMs: 1500,
    maxRanks: 3
  },
  {
    id: "warden_shieldwall",
    classId: "warden",
    tier: "weapon",
    weaponType: "warden_sword_board",
    slot: 3,
    name: "Shield Wall",
    description: "Brace behind your shield, absorbing incoming damage for a few seconds.",
    resource: "resolve",
    resourceCost: 15,
    cooldownMs: 9000,
    castTimeMs: 0,
    range: 0,
    radius: 0,
    effect: "buff",
    basePower: 25,
    powerScale: 0.6,
    ccDurationMs: 3000,
    maxRanks: 3
  },

  // -- Greataxe kit --
  {
    id: "warden_cleave",
    classId: "warden",
    tier: "weapon",
    weaponType: "warden_greataxe",
    slot: 1,
    name: "Cleave",
    description: "A wide axe swing striking all enemies around you.",
    resource: "resolve",
    resourceCost: 0,
    cooldownMs: 900,
    castTimeMs: 0,
    range: 0,
    radius: 3,
    effect: "aoe_damage",
    basePower: 6,
    powerScale: 0.5,
    maxRanks: 3
  },
  {
    id: "warden_rendingswing",
    classId: "warden",
    tier: "weapon",
    weaponType: "warden_greataxe",
    slot: 2,
    name: "Rending Swing",
    description: "A heavy overhead blow that tears deep.",
    resource: "resolve",
    resourceCost: 20,
    cooldownMs: 5000,
    castTimeMs: 0,
    range: 3,
    radius: 0,
    effect: "damage",
    basePower: 14,
    powerScale: 1.0,
    maxRanks: 3
  },
  {
    id: "warden_whirlwind",
    classId: "warden",
    tier: "weapon",
    weaponType: "warden_greataxe",
    slot: 3,
    name: "Whirlwind",
    description: "Spin, striking all nearby enemies.",
    resource: "resolve",
    resourceCost: 35,
    cooldownMs: 6000,
    castTimeMs: 300,
    range: 0,
    radius: 4.5,
    effect: "aoe_damage",
    basePower: 10,
    powerScale: 0.8,
    maxRanks: 3
  },

  // -- Utility (both kits) --
  {
    id: "warden_bulwark",
    classId: "warden",
    tier: "utility",
    slot: 4,
    name: "Bulwark",
    description: "Brace, gaining a shield that absorbs damage for a few seconds.",
    resource: "resolve",
    resourceCost: 30,
    cooldownMs: 14000,
    castTimeMs: 0,
    range: 0,
    radius: 0,
    effect: "buff",
    basePower: 40,
    powerScale: 1.2,
    ccDurationMs: 6000,
    maxRanks: 3
  },
  {
    id: "warden_secondwind",
    classId: "warden",
    tier: "utility",
    slot: 5,
    name: "Second Wind",
    description: "Tear victory from the brink, healing yourself.",
    resource: "resolve",
    resourceCost: 45,
    cooldownMs: 16000,
    castTimeMs: 0,
    range: 0,
    radius: 0,
    effect: "heal",
    basePower: 30,
    powerScale: 1.1,
    maxRanks: 3
  },

  // -- Elites --
  {
    id: "warden_unbreakable",
    classId: "warden",
    tier: "elite",
    specializationId: "warden_bulwark",
    special: "warden_unbreakable",
    slot: 6,
    name: "Unbreakable",
    description: "Halve incoming damage briefly and force nearby enemies to focus you.",
    resource: "resolve",
    resourceCost: 40,
    cooldownMs: 20000,
    castTimeMs: 0,
    range: 0,
    radius: 8,
    effect: "buff",
    basePower: 0.5,
    powerScale: 0,
    ccDurationMs: 4000,
    maxRanks: 3
  },
  {
    id: "warden_bloodrage",
    classId: "warden",
    tier: "elite",
    specializationId: "warden_berserker",
    special: "warden_bloodrage",
    slot: 6,
    name: "Bloodrage",
    description: "Sacrifice safety for power, gaining bonus power and lifesteal.",
    resource: "resolve",
    resourceCost: 40,
    cooldownMs: 20000,
    castTimeMs: 0,
    range: 0,
    radius: 0,
    effect: "buff",
    basePower: 0.4,
    powerScale: 0,
    ccDurationMs: 5000,
    maxRanks: 3
  },
  {
    id: "warden_ironcladstand",
    classId: "warden",
    tier: "elite",
    specializationId: "warden_sentinel",
    special: "warden_ironcladstand",
    slot: 6,
    name: "Ironclad Stand",
    description: "Cash in every hit you've weathered for a heavy shield, all at once.",
    resource: "resolve",
    resourceCost: 30,
    cooldownMs: 16000,
    castTimeMs: 0,
    range: 0,
    radius: 0,
    effect: "buff",
    basePower: 0,
    powerScale: 0,
    ccDurationMs: 6000,
    maxRanks: 3
  },

  // =========================================================================
  // RANGER — ranged, Focus
  // =========================================================================

  // -- Bow kit --
  {
    id: "ranger_quickshot",
    classId: "ranger",
    tier: "weapon",
    weaponType: "ranger_bow",
    slot: 1,
    name: "Quickshot",
    description: "A fast, accurate arrow.",
    resource: "focus",
    resourceCost: 0,
    cooldownMs: 600,
    castTimeMs: 0,
    range: 16,
    radius: 0,
    effect: "damage",
    basePower: 7,
    powerScale: 0.85,
    maxRanks: 3
  },
  {
    id: "ranger_volley",
    classId: "ranger",
    tier: "weapon",
    weaponType: "ranger_bow",
    slot: 2,
    name: "Piercing Volley",
    description: "Loose a volley that pierces everything in a line.",
    resource: "focus",
    resourceCost: 25,
    cooldownMs: 7000,
    castTimeMs: 200,
    range: 18,
    radius: 2,
    effect: "aoe_damage",
    basePower: 9,
    powerScale: 0.75,
    maxRanks: 3
  },
  {
    id: "ranger_barrage",
    classId: "ranger",
    tier: "weapon",
    weaponType: "ranger_bow",
    slot: 3,
    name: "Barrage",
    description: "Rain arrows down on a target area.",
    resource: "focus",
    resourceCost: 30,
    cooldownMs: 9000,
    castTimeMs: 400,
    range: 16,
    radius: 4,
    effect: "aoe_damage",
    basePower: 8,
    powerScale: 0.7,
    maxRanks: 3
  },

  // -- Dual Pistols kit --
  {
    id: "ranger_twinshot",
    classId: "ranger",
    tier: "weapon",
    weaponType: "ranger_pistols",
    slot: 1,
    name: "Twin Shot",
    description: "A fast double-tap at close range.",
    resource: "focus",
    resourceCost: 0,
    cooldownMs: 550,
    castTimeMs: 0,
    range: 10,
    radius: 0,
    effect: "damage",
    basePower: 7,
    powerScale: 0.8,
    maxRanks: 3
  },
  {
    id: "ranger_scatterblast",
    classId: "ranger",
    tier: "weapon",
    weaponType: "ranger_pistols",
    slot: 2,
    name: "Scatter Blast",
    description: "A close-range blast that staggers everything caught in it.",
    resource: "focus",
    resourceCost: 25,
    cooldownMs: 7000,
    castTimeMs: 0,
    range: 6,
    radius: 3,
    effect: "cc",
    basePower: 10,
    powerScale: 0.6,
    ccDurationMs: 900,
    maxRanks: 3
  },
  {
    id: "ranger_evasive",
    classId: "ranger",
    tier: "weapon",
    weaponType: "ranger_pistols",
    slot: 3,
    name: "Evasive Shot",
    description: "Leap back while firing, gaining brief evasion.",
    resource: "focus",
    resourceCost: 20,
    cooldownMs: 9000,
    castTimeMs: 0,
    range: 16,
    radius: 0,
    effect: "damage",
    basePower: 6,
    powerScale: 0.6,
    ccDurationMs: 1200,
    maxRanks: 3
  },

  // -- Utility (both kits) --
  {
    id: "ranger_trap",
    classId: "ranger",
    tier: "utility",
    slot: 4,
    name: "Explosive Trap",
    description: "Plant a trap that roots and damages enemies who trigger it.",
    resource: "focus",
    resourceCost: 30,
    cooldownMs: 10000,
    castTimeMs: 0,
    range: 6,
    radius: 3,
    effect: "cc",
    basePower: 14,
    powerScale: 0.9,
    ccDurationMs: 2000,
    maxRanks: 3
  },
  {
    id: "ranger_mark",
    classId: "ranger",
    tier: "utility",
    slot: 5,
    name: "Hunter's Mark",
    description: "Mark a target, increasing all damage it takes.",
    resource: "focus",
    resourceCost: 25,
    cooldownMs: 14000,
    castTimeMs: 0,
    range: 18,
    radius: 0,
    effect: "debuff",
    basePower: 0.25,
    powerScale: 0,
    ccDurationMs: 8000,
    maxRanks: 3
  },

  // -- Elites --
  {
    id: "ranger_windrunners_volley",
    classId: "ranger",
    tier: "elite",
    specializationId: "ranger_strider",
    slot: 6,
    name: "Windrunner's Volley",
    description: "Loose a burst of arrows in every direction.",
    resource: "focus",
    resourceCost: 35,
    cooldownMs: 14000,
    castTimeMs: 0,
    range: 0,
    radius: 6,
    effect: "aoe_damage",
    basePower: 9,
    powerScale: 0.6,
    maxRanks: 3
  },
  {
    id: "ranger_callthepack",
    classId: "ranger",
    tier: "elite",
    specializationId: "ranger_beastcaller",
    special: "ranger_callthepack",
    slot: 6,
    name: "Call the Pack",
    description: "Summon spirit wolves to join your hawk in harrying your target.",
    resource: "focus",
    resourceCost: 35,
    cooldownMs: 18000,
    castTimeMs: 0,
    range: 0,
    radius: 0,
    effect: "buff",
    basePower: 0,
    powerScale: 0,
    ccDurationMs: 8000,
    maxRanks: 3
  },
  {
    id: "ranger_tempestvolley",
    classId: "ranger",
    tier: "elite",
    specializationId: "ranger_windwalker",
    special: "ranger_tempestvolley",
    slot: 6,
    name: "Tempest Volley",
    description: "Spend every stack of Windrush on one devastating, piercing shot.",
    resource: "focus",
    resourceCost: 30,
    cooldownMs: 14000,
    castTimeMs: 0,
    range: 12,
    radius: 0,
    effect: "damage",
    basePower: 10,
    powerScale: 0.8,
    maxRanks: 3
  },

  // =========================================================================
  // MYSTIC — caster/healer, Aether
  // =========================================================================

  // -- Focus kit --
  {
    id: "mystic_moonbolt",
    classId: "mystic",
    tier: "weapon",
    weaponType: "mystic_focus",
    slot: 1,
    name: "Moonbolt",
    description: "Hurl a bolt of lunar energy.",
    resource: "aether",
    resourceCost: 8,
    cooldownMs: 900,
    castTimeMs: 200,
    range: 16,
    radius: 0,
    effect: "damage",
    basePower: 9,
    powerScale: 1.0,
    maxRanks: 3
  },
  {
    id: "mystic_nova",
    classId: "mystic",
    tier: "weapon",
    weaponType: "mystic_focus",
    slot: 2,
    name: "Lunar Nova",
    description: "Detonate a burst of Aether around a point.",
    resource: "aether",
    resourceCost: 30,
    cooldownMs: 7000,
    castTimeMs: 500,
    range: 14,
    radius: 4,
    effect: "aoe_damage",
    basePower: 11,
    powerScale: 0.9,
    maxRanks: 3
  },
  {
    id: "mystic_arcanesurge",
    classId: "mystic",
    tier: "weapon",
    weaponType: "mystic_focus",
    slot: 3,
    name: "Arcane Surge",
    description: "A fast bolt of raw Aether.",
    resource: "aether",
    resourceCost: 10,
    cooldownMs: 700,
    castTimeMs: 0,
    range: 16,
    radius: 0,
    effect: "damage",
    basePower: 7,
    powerScale: 0.8,
    maxRanks: 3
  },

  // -- Scythe kit --
  {
    id: "mystic_reap",
    classId: "mystic",
    tier: "weapon",
    weaponType: "mystic_scythe",
    slot: 1,
    name: "Reap",
    description: "A melee scythe strike that returns some of the damage dealt as health.",
    resource: "aether",
    resourceCost: 12,
    cooldownMs: 1400,
    castTimeMs: 0,
    range: 3,
    radius: 0,
    effect: "damage",
    basePower: 10,
    powerScale: 0.9,
    special: "mystic_reap",
    maxRanks: 3
  },
  {
    id: "mystic_darkharvest",
    classId: "mystic",
    tier: "weapon",
    weaponType: "mystic_scythe",
    slot: 2,
    name: "Dark Harvest",
    description: "Spin the scythe, cutting down everything nearby.",
    resource: "aether",
    resourceCost: 25,
    cooldownMs: 6500,
    castTimeMs: 300,
    range: 0,
    radius: 4,
    effect: "aoe_damage",
    basePower: 9,
    powerScale: 0.65,
    maxRanks: 3
  },
  {
    id: "mystic_gravitywell",
    classId: "mystic",
    tier: "weapon",
    weaponType: "mystic_scythe",
    slot: 3,
    name: "Gravity Well",
    description: "Pull nearby enemies together and root them briefly.",
    resource: "aether",
    resourceCost: 32,
    cooldownMs: 15000,
    castTimeMs: 400,
    range: 14,
    radius: 5,
    effect: "cc",
    basePower: 5,
    powerScale: 0.4,
    ccDurationMs: 1800,
    maxRanks: 3
  },

  // -- Utility (both kits) --
  {
    id: "mystic_healingtide",
    classId: "mystic",
    tier: "utility",
    slot: 4,
    name: "Healing Tide",
    description: "Wash healing energy over yourself and nearby allies.",
    resource: "aether",
    resourceCost: 35,
    cooldownMs: 9000,
    castTimeMs: 400,
    range: 0,
    radius: 8,
    effect: "aoe_heal",
    basePower: 16,
    powerScale: 1.1,
    maxRanks: 3
  },
  {
    id: "mystic_barrier",
    classId: "mystic",
    tier: "utility",
    slot: 5,
    name: "Barrier",
    description: "Shield yourself, absorbing a burst of incoming damage.",
    resource: "aether",
    resourceCost: 28,
    cooldownMs: 12000,
    castTimeMs: 0,
    range: 12,
    radius: 0,
    effect: "buff",
    basePower: 35,
    powerScale: 1.1,
    ccDurationMs: 6000,
    maxRanks: 3
  },

  // -- Elites --
  {
    id: "mystic_lunarsanctuary",
    classId: "mystic",
    tier: "elite",
    specializationId: "mystic_tidecaller",
    special: "mystic_lunarsanctuary",
    slot: 6,
    name: "Lunar Sanctuary",
    description: "Create a sanctuary of moonlight that heals allies standing within it.",
    resource: "aether",
    resourceCost: 40,
    cooldownMs: 18000,
    castTimeMs: 500,
    range: 0,
    radius: 5,
    effect: "aoe_heal",
    basePower: 8,
    powerScale: 0.3,
    ccDurationMs: 6000,
    maxRanks: 3
  },
  {
    id: "mystic_eclipse",
    classId: "mystic",
    tier: "elite",
    specializationId: "mystic_voidblade",
    slot: 6,
    name: "Eclipse",
    description: "Detonate a devastating burst of void energy around yourself.",
    resource: "aether",
    resourceCost: 45,
    cooldownMs: 18000,
    castTimeMs: 500,
    range: 0,
    radius: 5,
    effect: "aoe_damage",
    basePower: 14,
    powerScale: 0.9,
    maxRanks: 3
  },
  {
    id: "mystic_aegispulse",
    classId: "mystic",
    tier: "elite",
    specializationId: "mystic_wardweaver",
    special: "mystic_aegispulse",
    slot: 6,
    name: "Aegis Pulse",
    description: "Spend your built-up Aegis on a shield for yourself and every ally nearby.",
    resource: "aether",
    resourceCost: 35,
    cooldownMs: 18000,
    castTimeMs: 300,
    range: 0,
    radius: 6,
    effect: "aoe_heal",
    basePower: 0,
    powerScale: 0,
    ccDurationMs: 6000,
    maxRanks: 3
  },

  // =========================================================================
  // DUSKBLADE — burst melee, Umbra
  // =========================================================================

  // -- Twin Daggers kit --
  {
    id: "duskblade_twinstrike",
    classId: "duskblade",
    tier: "weapon",
    weaponType: "duskblade_daggers",
    slot: 1,
    name: "Twin Strike",
    description: "A fast double stab.",
    resource: "umbra",
    resourceCost: 0,
    cooldownMs: 650,
    castTimeMs: 0,
    range: 3,
    radius: 0,
    effect: "damage",
    basePower: 7,
    powerScale: 0.85,
    maxRanks: 3
  },
  {
    id: "duskblade_shadowstepslash",
    classId: "duskblade",
    tier: "weapon",
    weaponType: "duskblade_daggers",
    slot: 2,
    name: "Shadowstep Slash",
    description: "A heavier, opportunistic cut.",
    resource: "umbra",
    resourceCost: 22,
    cooldownMs: 6000,
    castTimeMs: 0,
    range: 4,
    radius: 0,
    effect: "damage",
    basePower: 15,
    powerScale: 1.0,
    maxRanks: 3
  },
  {
    id: "duskblade_umbralflurry",
    classId: "duskblade",
    tier: "weapon",
    weaponType: "duskblade_daggers",
    slot: 3,
    name: "Umbral Flurry",
    description: "Spin through everything close, blades first.",
    resource: "umbra",
    resourceCost: 30,
    cooldownMs: 6500,
    castTimeMs: 250,
    range: 0,
    radius: 3.5,
    effect: "aoe_damage",
    basePower: 8,
    powerScale: 0.6,
    maxRanks: 3
  },

  // -- Shadow Glaive kit --
  {
    id: "duskblade_glaivethrow",
    classId: "duskblade",
    tier: "weapon",
    weaponType: "duskblade_glaive",
    slot: 1,
    name: "Glaive Throw",
    description: "Hurl the glaive at a distant foe.",
    resource: "umbra",
    resourceCost: 0,
    cooldownMs: 700,
    castTimeMs: 0,
    range: 9,
    radius: 0,
    effect: "damage",
    basePower: 7,
    powerScale: 0.8,
    maxRanks: 3
  },
  {
    id: "duskblade_returningedge",
    classId: "duskblade",
    tier: "weapon",
    weaponType: "duskblade_glaive",
    slot: 2,
    name: "Returning Edge",
    description: "The glaive carves a line out and back.",
    resource: "umbra",
    resourceCost: 25,
    cooldownMs: 7000,
    castTimeMs: 200,
    range: 9,
    radius: 3,
    effect: "aoe_damage",
    basePower: 8,
    powerScale: 0.65,
    maxRanks: 3
  },
  {
    id: "duskblade_umbralpull",
    classId: "duskblade",
    tier: "weapon",
    weaponType: "duskblade_glaive",
    slot: 3,
    name: "Umbral Pull",
    description: "Yank a distant target off balance.",
    resource: "umbra",
    resourceCost: 22,
    cooldownMs: 9000,
    castTimeMs: 0,
    range: 9,
    radius: 0,
    effect: "cc",
    basePower: 6,
    powerScale: 0.5,
    ccDurationMs: 1500,
    maxRanks: 3
  },

  // -- Utility (both kits) --
  {
    id: "duskblade_vanish",
    classId: "duskblade",
    tier: "utility",
    slot: 4,
    name: "Vanish",
    description: "Slip into shadow, sharply reducing incoming damage briefly.",
    resource: "umbra",
    resourceCost: 30,
    cooldownMs: 14000,
    castTimeMs: 0,
    range: 0,
    radius: 0,
    effect: "buff",
    basePower: 0.5,
    powerScale: 0,
    special: "duskblade_vanish",
    ccDurationMs: 2500,
    maxRanks: 3
  },
  {
    id: "duskblade_umbralmend",
    classId: "duskblade",
    tier: "utility",
    slot: 5,
    name: "Umbral Mend",
    description: "Draw on banked Umbra to knit yourself back together.",
    resource: "umbra",
    resourceCost: 32,
    cooldownMs: 15000,
    castTimeMs: 0,
    range: 0,
    radius: 0,
    effect: "heal",
    basePower: 26,
    powerScale: 1.0,
    maxRanks: 3
  },

  // -- Elites --
  {
    id: "duskblade_vanishingstrike",
    classId: "duskblade",
    tier: "elite",
    specializationId: "duskblade_nightstalker",
    special: "duskblade_vanishingstrike",
    slot: 6,
    name: "Vanishing Strike",
    description: "A guaranteed critical strike from an opening no one else could see.",
    resource: "umbra",
    resourceCost: 35,
    cooldownMs: 16000,
    castTimeMs: 0,
    range: 3.5,
    radius: 0,
    effect: "damage",
    basePower: 18,
    powerScale: 1.15,
    maxRanks: 3
  },
  {
    id: "duskblade_crimsoneclipse",
    classId: "duskblade",
    tier: "elite",
    specializationId: "duskblade_bloodmoon",
    special: "duskblade_crimsoneclipse",
    slot: 6,
    name: "Crimson Eclipse",
    description: "A burst of bladework around you, healing you for a share of everything it cuts.",
    resource: "umbra",
    resourceCost: 42,
    cooldownMs: 18000,
    castTimeMs: 400,
    range: 0,
    radius: 5,
    effect: "aoe_damage",
    basePower: 12,
    powerScale: 0.8,
    maxRanks: 3
  },
  {
    id: "duskblade_cinderreap",
    classId: "duskblade",
    tier: "elite",
    specializationId: "duskblade_ashwalker",
    special: "duskblade_cinderreap",
    slot: 6,
    name: "Cinder Reap",
    description: "Strike your target and spend every stack of Ashfeed on a burst of healing.",
    resource: "umbra",
    resourceCost: 32,
    cooldownMs: 15000,
    castTimeMs: 0,
    range: 3.5,
    radius: 0,
    effect: "damage",
    basePower: 14,
    powerScale: 1.0,
    maxRanks: 3
  }
];

export function abilitiesForClass(classId: PlayerClassId): AbilityDef[] {
  return ABILITIES.filter((a) => a.classId === classId).sort((a, b) => a.slot - b.slot);
}

export function getAbility(id: string): AbilityDef | undefined {
  return ABILITIES.find((a) => a.id === id);
}

/**
 * The ability kit currently active for a character: 3 weapon abilities matching their
 * equipped weapon's type, 2 fixed utility abilities, and (once a specialization is chosen)
 * 1 elite ability — mirrors the hotbar 1-6.
 */
export function activeAbilities(character: Pick<CharacterState, "classId" | "equipment" | "specializationId">): AbilityDef[] {
  const weaponStack = character.equipment.weapon;
  const weaponDef = weaponStack ? getItem(weaponStack.itemId) : undefined;
  const weaponType = weaponDef?.weaponType;
  const all = abilitiesForClass(character.classId);

  const weaponAbilities = all.filter((a) => a.tier === "weapon" && a.weaponType === weaponType);
  const utilityAbilities = all.filter((a) => a.tier === "utility");
  const eliteAbilities = character.specializationId
    ? all.filter((a) => a.tier === "elite" && a.specializationId === character.specializationId)
    : [];

  return [...weaponAbilities, ...utilityAbilities, ...eliteAbilities].sort((a, b) => a.slot - b.slot);
}
